sudo: required
dist: trusty

language: node_js
node_js:
  - "stable"

addons:
  apt:
    packages:
      # install dependencies
      - graphicsmagick
      - imagemagick
      - poppler-utils
      - tesseract-ocr
      - libopencv-dev

script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- "test/**/*_spec.js" --reporter spec --recursive
  - mv test/test_files/benchmark benchmark/testdata
  - istanbul cover ./benchmark/image_preprocessors.js --report lcovonly --config ./benchmark/.istanbul.yml --  --only-gh-report opencv
  - bash <(curl -s https://codecov.io/bash) -s coverage -f *.info
  - "if [ -f benchmark/github-commit-status.json ]; then curl -H \"Authorization: token $GH_TOKEN\" -H \"Content-Type: application/json\" -X POST -d @benchmark/github-commit-status.json https://api.github.com/repos/danschultzer/receipt-scanner/statuses/$(git rev-parse HEAD); fi"
